In [2]:
import numpy as np

In [3]:
np.random.seed(seed=0)
arr = np.random.randint(low=1,high=150,size=30)
arr

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89, 141,  59,  40,
        88,  89,  82,  26,  78,  73,  10, 149, 116,  80,  83, 100,  30,
       148, 148, 143,  33])

In [4]:
arr_reshaped = arr.reshape(3,10)  # 2-d array, 3 x 10
arr_reshaped

array([[ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89],
       [141,  59,  40,  88,  89,  82,  26,  78,  73,  10],
       [149, 116,  80,  83, 100,  30, 148, 148, 143,  33]])

In [5]:
arr_reshaped = arr.reshape(3,2,5)  # 3-d array, 3x5x2
arr_reshaped

array([[[ 48, 118,  68, 104,  10],
        [ 22,  37,  88,  71,  89]],

       [[141,  59,  40,  88,  89],
        [ 82,  26,  78,  73,  10]],

       [[149, 116,  80,  83, 100],
        [ 30, 148, 148, 143,  33]]])

In [6]:
arr = np.arange(start=1,stop=9,step=1)
print(f"array: \n {arr} \n\n"
      f"array shape: {arr.shape}")

array: 
 [1 2 3 4 5 6 7 8] 

array shape: (8,)


In [8]:
arr_reshape = arr.reshape(-1,1)  

# it is a 2-d array because you passed a tuple with 2 items
# the -1 means 'unknown', so you don't know how many rows this 2-d array will have

print(f"array: \n {arr_reshape} \n\n"
      f"array shape: {arr_reshape.shape}")

array: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

array shape: (8, 1)


In [10]:
arr_reshape = arr.reshape(-1,2) 

print(f"array: \n {arr_reshape} \n\n"
      f"array shape: {arr_reshape.shape}")

array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

array shape: (4, 2)


In [11]:
aarr_reshape = arr.reshape(-1,3)  
# arr has 8 elements, it is not possible to reshape in 3 columns

ValueError: cannot reshape array of size 8 into shape (3)

In [12]:
np.random.seed(seed=0)
arr = np.random.randint(low=1,high=150,size=(2,5))
arr

array([[ 48, 118,  68, 104,  10],
       [ 22,  37,  88,  71,  89]])

In [14]:
arr_flatten = arr.flatten() # flatten need no arguments
arr_flatten

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [15]:
# Setting -1 at .reshape() indicates you want to reshape to a 1-d array but you dont tell the length, you let the computer calculate by itself
arr_reshape = arr.reshape(-1)
arr_reshape

array([ 48, 118,  68, 104,  10,  22,  37,  88,  71,  89])

In [17]:
arr.min()

10

In [18]:
arr.max()

118

In [19]:
arr.argmin()

4

In [20]:
arr.argmax()

1

In [23]:
arr = np.arange(start=1,stop=11,step=1).reshape(5,2)
print(
    f"* Array:\n {arr} \n\n"
    f"* Array shape: \n {arr.shape} \n\n"
    f"* Array type: \n {arr.dtype}"
    )
    

* Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

* Array shape: 
 (5, 2) 

* Array type: 
 int64


In [29]:
np.random.seed(seed=0)
arr = np.random.randn(2,4)
print(
    f"* Array:\n {arr} \n\n"
    f"* Array shape: \n {arr.shape} \n\n"
    f"* Array type: \n {arr.dtype}"
    )

* Array:
 [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]] 

* Array shape: 
 (2, 4) 

* Array type: 
 float64
