In [2]:
import numpy as np

In [3]:
np.random.seed(seed=10)
arr = np.random.randint(low=1,high=25, size=(3,5))
arr

array([[10,  5, 16,  1, 18],
       [17, 18,  9, 10,  1],
       [11,  9, 23,  5, 20]])

In [5]:
arr>4 # any element in array greater than 4

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [7]:
arr[arr>4] # outputs a 1d array of any true values

array([10,  5, 16, 18, 17, 18,  9, 10, 11,  9, 23,  5, 20])

In [8]:
arr[arr<6]

array([5, 1, 1, 5])

In [9]:
arr[(arr>4) & (arr <= 17)]

array([10,  5, 16, 17,  9, 10, 11,  9,  5])

In [10]:
arr[(arr<=5) | (arr>15)]

array([ 5, 16,  1, 18, 17, 18,  1, 23,  5, 20])

In [11]:
arr[ ((arr<=2)|(arr > 18)) | (arr == 9) ]

array([ 1,  9,  1,  9, 23, 20])