In [2]:
import numpy as np


In [3]:
arr = np.arange(start=1,stop=9,step=1)
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# write your code here
arr = np.arange(start=1,stop=10,step=1)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.arange(start=1,stop=9,step= 1.5 )
arr

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [6]:
arr = np.arange(start=1,stop=9,step= .5 )
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5])

In [7]:
arr = np.arange(start=15,stop=9,step= -1 )
arr

array([15, 14, 13, 12, 11, 10])

In [8]:
arr = np.arange(start=1,stop=12,step= 1.5 )
arr

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5])

In [9]:
arr = np.zeros(shape=(2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr = np.zeros(shape=(2,2,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
arr = np.ones(shape=(2,5)) 
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# A similar function to np.arange() is np.linspace(), but instead of step argument, there is num argument, num is the number of samples that need to be retrieved in that interval.
arr = np.linspace(start=1,stop=5,num=9)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [14]:
arr = np.linspace(start=10,stop=50,num=10)
arr

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [15]:
arr = np.linspace(start=-3,stop=5,num=9)
arr

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [17]:
arr = np.random.rand(2,2)  # random 2-d array
arr

array([[0.15597958, 0.99725542],
       [0.1337404 , 0.84065861]])

In [18]:
arr = np.random.rand(3,4,2)  # 3-d array
arr

array([[[0.13603255, 0.58212227],
        [0.04687248, 0.42185328],
        [0.76573339, 0.26308613],
        [0.68031956, 0.65643065]],

       [[0.72625921, 0.55685166],
        [0.34637301, 0.85722076],
        [0.7686647 , 0.54051173],
        [0.81620772, 0.73062356]],

       [[0.08506128, 0.99727832],
        [0.35826516, 0.67185322],
        [0.76946414, 0.50680737],
        [0.90484867, 0.07542723]]])

In [19]:
arr = np.random.randn(8,2) # 2-d array with 8 rows and 2 columns
arr

array([[ 1.02563096, -1.60928485],
       [ 0.85820866,  1.22537954],
       [-0.05493441,  0.11153241],
       [ 0.06811299, -0.1791325 ],
       [ 0.11052507, -2.24393551],
       [ 0.56841193,  2.37351247],
       [ 1.64242904, -0.15359621],
       [ 0.60827833,  1.60132914]])

In [20]:
arr = np.random.randn(25 ) # 1-d array with 25 elements
arr

array([-0.93902303,  0.62817301, -1.58450512, -0.14368643,  0.18375961,
        0.26259739, -1.28268195,  0.32129398, -1.29078151,  0.16809825,
       -0.03682844, -2.33835307,  0.23355759, -0.85518509,  0.01089243,
        2.11622328,  0.78824534, -0.48283783,  0.70854203, -0.21090824,
       -0.07754485,  0.21655959,  1.08336517,  2.01465548,  0.56101317])

In [21]:
arr = np.random.randint(low=10,high=50,size=5) # 1-d array, shape: 5 elements
arr 

array([39, 23, 10, 10, 28])

In [22]:
arr = np.random.randint(low=250,high=888,size=(4,3)) # 2-d array, shape: 4 rows x 3 columns
arr 

array([[427, 843, 512],
       [759, 700, 729],
       [849, 351, 334],
       [863, 458, 839]])

In [23]:
arr = np.random.randint(low=250,high=888,size=( 2,3,2 ))
arr

array([[[687, 807],
        [758, 712],
        [596, 827]],

       [[864, 731],
        [514, 712],
        [699, 253]]])

In [24]:
np.random.seed(seed=1)
arr = np.random.randint(low=10,high=50,size=5)
arr

array([47, 22, 18, 19, 21])