In [1]:
import numpy as np

In [8]:
np.random.seed(seed=2)
arr1 = np.random.randint(low=0,high=8,size=(3,5))
arr1

array([[0, 7, 5, 0, 6],
       [3, 2, 3, 0, 7],
       [2, 1, 7, 3, 5]])

In [9]:
np.random.seed(seed=1)
arr2 = np.random.randint(low=0,high=50,size=(3,5))
arr2

array([[37, 43, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 45,  6]])

In [10]:
arr2 + 2

array([[39, 45, 14, 10, 11],
       [13,  7, 17,  2, 18],
       [ 3, 14,  9, 47,  8]])

In [11]:
arr1 / 7

array([[0.        , 1.        , 0.71428571, 0.        , 0.85714286],
       [0.42857143, 0.28571429, 0.42857143, 0.        , 1.        ],
       [0.28571429, 0.14285714, 1.        , 0.42857143, 0.71428571]])

In [13]:
arr1**2

array([[ 0, 49, 25,  0, 36],
       [ 9,  4,  9,  0, 49],
       [ 4,  1, 49,  9, 25]])

In [14]:
arr1 + arr2

array([[37, 50, 17,  8, 15],
       [14,  7, 18,  0, 23],
       [ 3, 13, 14, 48, 11]])

In [15]:
arr2 - arr1

array([[37, 36,  7,  8,  3],
       [ 8,  3, 12,  0,  9],
       [-1, 11,  0, 42,  1]])

In [16]:
arr1/arr2

/tmp/ipykernel_1835/3323896316.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr1/arr2


array([[0.        , 0.1627907 , 0.41666667, 0.        , 0.66666667],
       [0.27272727, 0.4       , 0.2       ,        nan, 0.4375    ],
       [2.        , 0.08333333, 1.        , 0.06666667, 0.83333333]])

In [17]:
1/arr2

/tmp/ipykernel_1835/1672552411.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr2


array([[0.02702703, 0.02325581, 0.08333333, 0.125     , 0.11111111],
       [0.09090909, 0.2       , 0.06666667,        inf, 0.0625    ],
       [1.        , 0.08333333, 0.14285714, 0.02222222, 0.16666667]])

In [19]:
np.random.seed(seed=101)
arr = np.random.randint(low=-10,high=25,size=(3,5))
arr

array([[ 21,   1,   7,  -4,  13],
       [  1,  -1,   3,  -6,  18],
       [-10,  -5,   2,  19,   9]])

In [20]:
np.sqrt(arr)

/tmp/ipykernel_1835/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[4.58257569, 1.        , 2.64575131,        nan, 3.60555128],
       [1.        ,        nan, 1.73205081,        nan, 4.24264069],
       [       nan,        nan, 1.41421356, 4.35889894, 3.        ]])

In [21]:
np.abs(arr)

array([[21,  1,  7,  4, 13],
       [ 1,  1,  3,  6, 18],
       [10,  5,  2, 19,  9]])

In [22]:
np.exp2(arr) #calculate the exponential in base 2 (2 ** x) of all elements

array([[2.097152e+06, 2.000000e+00, 1.280000e+02, 6.250000e-02,
        8.192000e+03],
       [2.000000e+00, 5.000000e-01, 8.000000e+00, 1.562500e-02,
        2.621440e+05],
       [9.765625e-04, 3.125000e-02, 4.000000e+00, 5.242880e+05,
        5.120000e+02]])

In [23]:
np.log(arr)

/tmp/ipykernel_1835/3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[3.04452244, 0.        , 1.94591015,        nan, 2.56494936],
       [0.        ,        nan, 1.09861229,        nan, 2.89037176],
       [       nan,        nan, 0.69314718, 2.94443898, 2.19722458]])

In [24]:
np.log2(arr)

/tmp/ipykernel_1835/1405652587.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr)


array([[4.39231742, 0.        , 2.80735492,        nan, 3.70043972],
       [0.        ,        nan, 1.5849625 ,        nan, 4.169925  ],
       [       nan,        nan, 1.        , 4.24792751, 3.169925  ]])

In [25]:
np.log10(arr)

/tmp/ipykernel_1835/2153533263.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([[1.32221929, 0.        , 0.84509804,        nan, 1.11394335],
       [0.        ,        nan, 0.47712125,        nan, 1.25527251],
       [       nan,        nan, 0.30103   , 1.2787536 , 0.95424251]])

In [26]:
np.std(arr) #standard deviation for the array

9.344279295673667

In [28]:
 # mean for the array
 np.mean(arr) 

4.533333333333333

In [30]:
np.median(arr)

2.0

In [31]:
np.max(arr)

21

In [32]:
np.min(arr)

-10

In [33]:
np.sum(arr)

68

In [35]:
np.sum(arr,axis=0) # sum the columns

array([12, -5, 12,  9, 40])

In [36]:
np.sum(arr,axis=1) # sum the rows

array([38, 15, 15])