In [2]:
import numpy as np

In [3]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=9)
arr

array([41, 21, 27, 16, 33, 21, 19, 23, 14])

In [4]:
arr[-3:]

array([19, 23, 14])

In [5]:
arr[-3:-1]


array([19, 23])

In [6]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,5))
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [7]:
arr[:,-2:]

array([[16, 33],
       [14, 38],
       [39, 29]])

In [8]:
arr[1:3,-3:-1]

array([[23, 14],
       [22, 39]])

In [9]:
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,5,4))
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23],
        [14, 38, 10, 15],
        [22, 39, 29, 18],
        [39, 44, 18, 29]],

       [[20, 22, 41, 33],
        [10, 19, 18, 46],
        [29, 45, 38, 17],
        [20, 49, 48, 19],
        [28, 17, 49, 25]],

       [[10, 22, 27, 21],
        [25, 43, 39, 34],
        [46, 29, 45, 40],
        [20, 49, 30, 37],
        [18, 32, 36, 33]]])

In [10]:
arr[1,2:4,-3:]

array([[45, 38, 17],
       [49, 48, 19]])