In [1]:
import numpy as np

In [2]:
arr = np.arange(start=0,stop=26,step=2)
arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [3]:
arr[8]

16

In [4]:
arr[0]

0

In [5]:
arr[1:5]

array([2, 4, 6, 8])

In [6]:
arr[0:5]

array([0, 2, 4, 6, 8])

In [7]:
arr[5:9]

array([10, 12, 14, 16])

In [8]:
arr[:5]

array([0, 2, 4, 6, 8])

In [9]:
arr[7:]

array([14, 16, 18, 20, 22, 24])

In [11]:
# 2d arrary slicing
np.random.seed(seed=101) 
arr = np.random.randint(low=10,high=50,size=(3,5))
arr

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29]])

In [12]:
arr[1,0]

21

In [13]:
arr[1,:]

array([21, 19, 23, 14, 38])

In [14]:
arr[0:3,3]

array([16, 14, 39])

In [15]:
arr[1:,3:]

array([[14, 38],
       [39, 29]])

In [16]:
# 3d array slicing
np.random.seed(seed=101)
arr = np.random.randint(low=10,high=50,size=(3,3,4))  # 3-d array: in this case, 3 arrays of 3x4
arr

array([[[41, 21, 27, 16],
        [33, 21, 19, 23],
        [14, 38, 10, 15]],

       [[22, 39, 29, 18],
        [39, 44, 18, 29],
        [20, 22, 41, 33]],

       [[10, 19, 18, 46],
        [29, 45, 38, 17],
        [20, 49, 48, 19]]])

In [17]:
arr[1,0,0]

22

In [18]:
arr[0,:,2]

array([27, 19, 10])

In [19]:
arr[0,:2,:3]

array([[41, 21, 27],
       [33, 21, 19]])

In [20]:
arr[0:2,:2,:3]

array([[[41, 21, 27],
        [33, 21, 19]],

       [[22, 39, 29],
        [39, 44, 18]]])

In [21]:
arr[1:3,:,1:3]

array([[[39, 29],
        [44, 18],
        [22, 41]],

       [[19, 18],
        [45, 38],
        [49, 48]]])