In [1]:
import numpy as np

In [2]:
my_list = [7, 9, 88, 4621]
my_list

[7, 9, 88, 4621]

In [3]:
type(my_list)

list

In [4]:
arr = np.array(my_list)
arr

array([   7,    9,   88, 4621])

In [5]:
my_list = ['text','label_example',55,150,'final_text_example']
my_list

['text', 'label_example', 55, 150, 'final_text_example']

In [6]:
arr = np.array(my_list)
arr

array(['text', 'label_example', '55', '150', 'final_text_example'],
      dtype='<U21')

In [7]:
print(f"* The index 0 is:  {my_list[0]}  and its data type is {type(my_list[0])}")
print(f"* The index 2 is:  {my_list[2]}  and its data type is {type(my_list[2])}")


* The index 0 is:  text  and its data type is <class 'str'>
* The index 2 is:  55  and its data type is <class 'int'>


In [8]:
arr = np.array(my_list)
arr

array(['text', 'label_example', '55', '150', 'final_text_example'],
      dtype='<U21')

In [9]:
arr = np.array(my_list,dtype=object)
arr

array(['text', 'label_example', 55, 150, 'final_text_example'],
      dtype=object)

In [10]:
my_list = [1, 1.5]
my_list

[1, 1.5]

In [11]:
# write your code 
arr = np.array(my_list)


In [12]:
arr.dtype

dtype('float64')

In [13]:
my_list = [ [1,2,3],[4,5,6]]  # write the list here
my_list

[[1, 2, 3], [4, 5, 6]]

In [14]:
arr = np.array([[ 10,  80,  77], [ 99,  99,  99],[777, 999, 787]])
arr

array([[ 10,  80,  77],
       [ 99,  99,  99],
       [777, 999, 787]])

In [15]:
words = np.array(['bacon', 'egg', 'spam'])
words

array(['bacon', 'egg', 'spam'], dtype='<U5')

In [16]:
my_2dlist = [[1,2,3],[4,5,6]] # 2-d python list
arr = np.array(my_2dlist)  # create your 2-d array
arr

array([[1, 2, 3],
       [4, 5, 6]])